//! Auto-generated API endpoint: {{API_NAME}}
//! Generated by zmodu api — extend with business routes.

const std = @import("std");
const http = @import("zigmodu").http;

pub const {{PASCAL_NAME}}Api = struct {
    pub fn init(group: *http.http_server.RouteGroup) !void {
        try group.get("/{{API_NAME}}s", list, null);
        try group.get("/{{API_NAME}}s/{id}", get, null);
        try group.post("/{{API_NAME}}s", create, null);
        try group.put("/{{API_NAME}}s/{id}", update, null);
        try group.delete("/{{API_NAME}}s/{id}", delete_, null);
    }

    fn list(ctx: *http.http_server.Context) !void {
        try ctx.json(200, "{{\"message\": \"GET /{{API_NAME}}s\"}}");
    }

    fn get(ctx: *http.http_server.Context) !void {
        const id = ctx.params.get("id") orelse return error.BadRequest;
        try ctx.jsonStruct(200, .{ .id = id });
    }

    fn create(ctx: *http.http_server.Context) !void {
        _ = ctx;
        try ctx.json(201, "{{\"message\": \"CREATE /{{API_NAME}}s\"}}");
    }

    fn update(ctx: *http.http_server.Context) !void {
        _ = ctx;
        try ctx.json(200, "{{\"message\": \"UPDATE /{{API_NAME}}s\"}}");
    }

    fn delete_(ctx: *http.http_server.Context) !void {
        _ = ctx;
        try ctx.json(204, "");
    }
};
