//! Auto-generated event handler: {{EVENT_NAME}}
//! Generated by zmodu event — extend with domain logic.

const std = @import("std");

pub const {{PASCAL_NAME}}Event = struct {
    id: u64,
    timestamp: i64,
    data: []const u8,
};

pub fn handle{{PASCAL_NAME}}(event: {{PASCAL_NAME}}Event) void {
    std.log.info("Handling {{EVENT_NAME}} event: id={}", .{event.id});
    // TODO: Add event handling logic
}
