//! Auto-generated HTTP API for module `<<MODULE_NAME>>`.
//! Generated by zmodu — uses zigmodu.http domain with best-practice middleware.

const std = @import("std");
const http = @import("zigmodu").http;
const service = @import("service.zig");
const model = @import("model.zig");

pub const <<PASCAL_MODULE>>Api = struct {
    service: *service.<<PASCAL_MODULE>>Service,

    pub fn init(svc: *service.<<PASCAL_MODULE>>Service) <<PASCAL_MODULE>>Api {
        return .{ .service = svc };
    }

    /// Register all routes on a RouteGroup. Middleware chain:
    ///   requestId → csrf → auth → handler
    pub fn registerRoutes(self: *<<PASCAL_MODULE>>Api, group: *http.RouteGroup) !void {
