//! Architecture tests for `<<MODULE_NAME>>` module (auto-generated by zmodu).
//! Verifies module contracts, dependency integrity, and naming conventions.

const std = @import("std");
const zigmodu = @import("zigmodu");

test "<<MODULE_NAME>> - architecture: no self dependency" {
    const info = zigmodu.ModuleInfo.init("<<MODULE_NAME>>", "<<MODULE_NAME>> module", <<DEPS>>);
    for (info.deps) |dep| {
        if (std.mem.eql(u8, dep, info.name)) {
            std.log.err("Module '{s}' depends on itself", .{info.name});
            return error.SelfDependency;
        }
    }
}

test "<<MODULE_NAME>> - architecture: naming convention" {
    const info = zigmodu.ModuleInfo.init("<<MODULE_NAME>>", "<<MODULE_NAME>> module", <<DEPS>>);
    // Module names should be lowercase ASCII with optional underscores
    for (info.name) |c| {
        try std.testing.expect(std.ascii.isLower(c) or c == '_' or std.ascii.isDigit(c));
    }
}

test "<<MODULE_NAME>> - architecture: dependency limit" {
    const info = zigmodu.ModuleInfo.init("<<MODULE_NAME>>", "<<MODULE_NAME>> module", <<DEPS>>);
    try std.testing.expect(info.deps.len <= 10);
}
