//! Architecture tests for `<<MODULE_NAME>>` module (auto-generated by zmodu).
//! Verifies module contracts, dependency integrity, and naming conventions.

const std = @import("std");
const zigmodu = @import("zigmodu");

test "<<MODULE_NAME>> - architecture: no self dependency" {
    const allocator = std.testing.allocator;
    var modules = zigmodu.ApplicationModules.init(allocator);
    defer modules.deinit();

    try modules.register(zigmodu.ModuleInfo.init("<<MODULE_NAME>>", "<<MODULE_NAME>> module", <<DEPS>>));

    var tester = zigmodu.ArchitectureTester.init(allocator, &modules);
    defer tester.deinit();

    try tester.ruleNoSelfDependency();
    try std.testing.expectEqual(@as(usize, 0), tester.getViolationCountBySeverity(.err));
}

test "<<MODULE_NAME>> - architecture: naming convention" {
    const allocator = std.testing.allocator;
    var modules = zigmodu.ApplicationModules.init(allocator);
    defer modules.deinit();

    try modules.register(zigmodu.ModuleInfo.init("<<MODULE_NAME>>", "<<MODULE_NAME>> module", <<DEPS>>));

    var tester = zigmodu.ArchitectureTester.init(allocator, &modules);
    defer tester.deinit();

    try tester.ruleModuleNamingConvention();
    try std.testing.expectEqual(@as(usize, 0), tester.getViolationCountBySeverity(.err));
}

test "<<MODULE_NAME>> - architecture: dependency limit" {
    const allocator = std.testing.allocator;
    var modules = zigmodu.ApplicationModules.init(allocator);
    defer modules.deinit();

    try modules.register(zigmodu.ModuleInfo.init("<<MODULE_NAME>>", "<<MODULE_NAME>> module", <<DEPS>>));

    var tester = zigmodu.ArchitectureTester.init(allocator, &modules);
    defer tester.deinit();

    try tester.ruleLimitedDependencies(10);
    try std.testing.expectEqual(@as(usize, 0), tester.getViolationCountBySeverity(.err));
}
