//! <<MODULE_NAME>> module — generated by zmodu.
//!
//! Lifecycle: init() → service ready → deinit() on shutdown.

const std = @import("std");
const api = @import("zigmodu").api;
const http = @import("zigmodu").http;

pub const info = api.Module{
    .name = "<<MODULE_NAME>>",
    .description = "<<MODULE_NAME>> module",
    .dependencies = <<DEPS>>,
    .is_internal = false,
};

pub fn init() !void {
    std.log.info("[{s}] initializing", .{info.name});
}

pub fn deinit() void {
    std.log.info("[{s}] shutting down", .{info.name});
}

pub fn healthCheck(ctx: *http.http_server.Context) !void {
    try ctx.json(200, "{\"status\":\"UP\",\"module\":\"<<MODULE_NAME>>\"}");
}
