//! ZigModu module `<<MODULE_NAME>>` — generated by zmodu.
//!
//! Lifecycle: init() → service ready → deinit() on shutdown.
//! See: https://github.com/chy3xyz/zigmodu/docs/API-MIGRATION.md

const std = @import("std");
const zigmodu = @import("zigmodu");

pub const info = zigmodu.api.Module{
    .name = "<<MODULE_NAME>>",
    .description = "<<MODULE_NAME>> module",
    .dependencies = <<DEPS>>,
};

// ── Configuration ──────────────────────────────────────────
pub const Config = struct {
    // Add module-specific settings here.
    // Use zigmodu.data.ExternalizedConfig to load from env/file.
};

var config: Config = .{};

/// Set configuration before init(). Call once at startup.
pub fn configure(cfg: Config) void {
    config = cfg;
}

// ── Lifecycle ──────────────────────────────────────────────
pub fn init() !void {
    std.log.info("[{s}] initializing", .{info.name});
    <<INIT_EVENTS>>
}

pub fn deinit() void {
    std.log.info("[{s}] shutting down", .{info.name});
}

<<EVENTS_SECTION>>

// ── Health Check ───────────────────────────────────────────
pub fn registerHealthChecks(endpoint: *zigmodu.HealthEndpoint) !void {
    try endpoint.registerCheck("<<MODULE_NAME>>", "Module health", struct {
        fn check(_: ?*anyopaque) zigmodu.HealthEndpoint.HealthStatus {
            return .UP;
        }
    }.check);
}
