//! ⛔ @generated by zmodu — DO NOT EDIT
//!
//! ORM persistence for module: <<MODULE_NAME>>
//! ✅ Extend in: ext/service.zig, ext/api.zig

const std = @import("std");
const data = @import("zigmodu").data;
const model = @import("model.zig");

pub const <<PASCAL_MODULE>>Persistence = struct {
    backend: data.SqlxBackend,
    orm: data.orm.Orm(data.SqlxBackend),

    pub fn init(backend: data.SqlxBackend) <<PASCAL_MODULE>>Persistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }
