//! Auto-generated ORM persistence for module: <<MODULE_NAME>>
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const <<PASCAL_MODULE>>Persistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) <<PASCAL_MODULE>>Persistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

