//! Service layer for module `<<MODULE_NAME>>`.
//! Generated by zmodu — CRUD delegation with event hook points.

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const <<PASCAL_MODULE>>Service = struct {
    persistence: *persistence.<<PASCAL_MODULE>>Persistence,
    event_bus: ?*zigmodu.TypedEventBus(<<PASCAL_MODULE>>Event) = null,

    pub fn init(p: *persistence.<<PASCAL_MODULE>>Persistence) <<PASCAL_MODULE>>Service {
        return .{ .persistence = p };
    }

    pub fn withEvents(self: *<<PASCAL_MODULE>>Service, bus: *zigmodu.TypedEventBus(<<PASCAL_MODULE>>Event)) void {
        self.event_bus = bus;
    }

    // Event hooks — emit after persistence operations:
    fn afterCreate(self: *<<PASCAL_MODULE>>Service, entity: anytype) void {
        if (self.event_bus) |bus| bus.publish(.{ .created = .{ .id = entity.id } });
    }

