//! Auto-generated service for module: <<MODULE_NAME>>
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=<<MODULE_NAME>> | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const <<PASCAL_MODULE>>Service = struct {
    persistence: *persistence.<<PASCAL_MODULE>>Persistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(<<PASCAL_MODULE>>Event),

    pub fn init(persistence_ptr: *persistence.<<PASCAL_MODULE>>Persistence) <<PASCAL_MODULE>>Service {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *<<PASCAL_MODULE>>Service, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *<<PASCAL_MODULE>>Service, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *<<PASCAL_MODULE>>Service, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

