//! Auto-generated zent Client for module: <<MODULE_NAME>>
//! Generated by zmodu orm --backend zent
//! Do not modify manually

const std = @import("std");
const zent = @import("zent");

pub fn makeClient(allocator: std.mem.Allocator, drv: anytype) !zent.codegen.client.Client {
    const graph = comptime zent.codegen.graph.buildGraph(&.{ 