//! ZigModu module definition for: <<MODULE_NAME>>
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/zent/

const std = @import("std");
const zigmodu = @import("zigmodu");

pub const info = zigmodu.api.Module{
    .name = "<<MODULE_NAME>>",
    .description = "<<MODULE_NAME>> module (zent)",
    .dependencies = &.{},
    .is_internal = false,
};

pub fn init() !void {
    std.log.info("{s} module initialized", .{"<<MODULE_NAME>>"});
}

pub fn deinit() void {
    std.log.info("{s} module cleaned up", .{"<<MODULE_NAME>>"});
}
